/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import classes.Funcionario;
import conexoes.MySQL;
import java.util.HashSet;
import java.util.Vector;
import javax.swing.JOptionPane;
/**
 *
 * @author fekwa
 */
public class CadastroFuncionario extends javax.swing.JFrame {
 MySQL conectar = new MySQL();
    Funcionario novoFuncionario = new Funcionario();
    String cargoRecebido = "null";
    String userRecebido = "null";
    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
        resgatarEmpresas();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_Cpf = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        txt_rg = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JTextField();
        cmb_cargo = new javax.swing.JComboBox<>();
        txt_senha = new javax.swing.JTextField();
        cmb_sexo = new javax.swing.JComboBox<>();
        txt_salario = new javax.swing.JTextField();
        cmb_estadoCivil = new javax.swing.JComboBox<>();
        txt_confirmaSenha = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        cmb_Empresa = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txt_pesquisaCPF = new javax.swing.JTextField();
        txt_pesquisaRG = new javax.swing.JTextField();
        txt_pesquisaNome = new javax.swing.JTextField();
        txt_pesquisaEmail = new javax.swing.JTextField();
        txt_pesquisaEndereco = new javax.swing.JTextField();
        txt_pesquisaTelefone = new javax.swing.JTextField();
        txt_pesquisaCargo = new javax.swing.JTextField();
        txt_pesquisaSenha = new javax.swing.JTextField();
        txt_pesquisaSexo = new javax.swing.JTextField();
        txt_pesquisaEstadoCivil = new javax.swing.JTextField();
        txt_pesquisaSalario = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        btn_pesquisalimpar = new javax.swing.JButton();
        cmb_pesquisaEmpresa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Funcionario"));

        txt_Cpf.setText("CPF");

        txt_nome.setText("Nome");

        txt_rg.setText("RG");

        txt_email.setText("Email");

        txt_telefone.setText("Telefone");

        txt_endereco.setText("Endereco");

        cmb_cargo.setBackground(new java.awt.Color(204, 204, 204));
        cmb_cargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tecnico", "Contabilidade", "Suporte", "Consultoria", "Adm" }));
        cmb_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cargoActionPerformed(evt);
            }
        });

        txt_senha.setText("Senha");

        cmb_sexo.setBackground(new java.awt.Color(204, 204, 204));
        cmb_sexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "HELICOPTERO", "ADM", "Masculino", "Feminino" }));
        cmb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sexoActionPerformed(evt);
            }
        });

        txt_salario.setText("salario");

        cmb_estadoCivil.setBackground(new java.awt.Color(204, 204, 204));
        cmb_estadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casado(a)", "Solteiro(a)", "Viuvo(a)", "TRABALHO" }));
        cmb_estadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estadoCivilActionPerformed(evt);
            }
        });

        txt_confirmaSenha.setText("Senha");

        btn_cadastrar.setText("CADASTRAR");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPAR");

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        cmb_Empresa.setBackground(new java.awt.Color(204, 204, 204));
        cmb_Empresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cmb_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_salario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_senha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_confirmaSenha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nome)
                                .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_email)
                                .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_endereco)
                                .addComponent(cmb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_cadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_voltar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmb_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txt_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(jButton2)
                    .addComponent(btn_voltar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Funcionario"));

        txt_pesquisaCPF.setText("CPF");

        txt_pesquisaRG.setText("RG");

        txt_pesquisaNome.setText("Nome");

        txt_pesquisaEmail.setText("Email");
        txt_pesquisaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisaEmailActionPerformed(evt);
            }
        });

        txt_pesquisaEndereco.setText("Endereco");

        txt_pesquisaTelefone.setText("Telefone");

        txt_pesquisaCargo.setText("Cargo");

        txt_pesquisaSenha.setText("Senha");

        txt_pesquisaSexo.setText("Sexo");

        txt_pesquisaEstadoCivil.setText("Estado civil");

        txt_pesquisaSalario.setText("salario");

        btn_pesquisar.setText("PESQUISAR");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_atualizar.setText("ATUALIZAR");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_apagar.setText("APAGAR");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        btn_pesquisalimpar.setText("LIMPAR");

        cmb_pesquisaEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        cmb_pesquisaEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_pesquisaEmpresa.setEnabled(false);
        cmb_pesquisaEmpresa.setFocusable(false);
        cmb_pesquisaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pesquisaEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_pesquisaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_pesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_apagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pesquisalimpar))
                    .addComponent(txt_pesquisaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaRG, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txt_pesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pesquisaRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txt_pesquisaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesquisaEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_pesquisaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesquisar)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_apagar)
                    .addComponent(btn_pesquisalimpar))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_estadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estadoCivilActionPerformed

    private void cmb_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cargoActionPerformed

    private void cmb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sexoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        if(txt_senha.getText().equals(txt_confirmaSenha.getText())){
            CadastrarFuncionario(novoFuncionario);
        }else{System.out.println("SENHAS ERRADAS");}
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
       Menu menuzinho = new Menu();
       menuzinho.Recebe(userRecebido, cargoRecebido);
       menuzinho.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void txt_pesquisaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisaEmailActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        PesquisarFuncionario(novoFuncionario);
        
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        DeletaFuncionario(novoFuncionario);
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        atualizaFuncionario(novoFuncionario);
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void cmb_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_EmpresaActionPerformed

    private void cmb_pesquisaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pesquisaEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_pesquisaEmpresaActionPerformed
    
    private void atualizaFuncionario(Funcionario novo){
        this.conectar.conectaBanco();
        String consultaCpf = this.txt_pesquisaCPF.getText ();
        //nome,rg,email,telefone,endereco,cargo,senha,sexo,salario,estado_civil,cpf
        
        novo.setNome(txt_pesquisaNome.getText());
        novo.setCpf(txt_pesquisaCPF.getText());
        novo.setSenha(txt_pesquisaSenha.getText());
        novo.setEmail(txt_pesquisaEmail.getText());
        novo.setCargo(txt_pesquisaCargo.getText());
        novo.setEndereco(txt_pesquisaEndereco.getText());
        novo.setEstado_civil(txt_pesquisaEstadoCivil.getText());
        novo.setSexo(txt_pesquisaSexo.getText());
        novo.setRg(txt_pesquisaRG.getText());
        novo.setSalario(txt_pesquisaSalario.getText());
        novo.setTelefone(txt_pesquisaTelefone.getText());
        
        try{
            var atualizarCliente = ""
                    + "Update Funcionario set "
                    + "nome = '" + novo.getNome() + "',"
                    + "rg = '" + novo.getRg() + "',"
                    + "email = '" + novo.getEmail() + "',"
                    + "telefone = '" + novo.getTelefone() + "',"
                    + "endereco = '" + novo.getEndereco() + "',"
                    + "cargo = '" + novo.getCargo() + "',"
                    + "senha = '" + novo.getSenha() + "',"
                    + "sexo = '" + novo.getSexo() + "',"
                    + "salario = '" + novo.getSalario()  + "',"
                    + "estado_civil = '" + novo.getEstado_civil() + "'"
                    + " WHERE cpf = '" + consultaCpf + "';"
                    ;
            this.conectar.updateSQL(atualizarCliente);
            
        }catch(Exception e){
        
        }
    }
    
    private void DeletaFuncionario(Funcionario novo){
        this.conectar.conectaBanco();
        
        String consultaCpf = this.txt_pesquisaCPF.getText();
        
        try{
            var deletarCpf = "DELETE from Funcionario where cpf = '" + consultaCpf + "'";
                           
            this.conectar.updateSQL (deletarCpf);
            System.out.println(deletarCpf);
            
            
            
        } catch (Exception e) {
            System.out.println("Erro ao Deletar Cliente"+ e.getMessage());
            JOptionPane.showMessageDialog (null, "Erro ao Deletar Funcionario");
        }
    }
    
    private void PesquisarFuncionario(Funcionario novo){
        this.conectar.conectaBanco(); //estabelecendo conexão com o bd
        String pesquisaCpf = txt_pesquisaCPF.getText();
        
        try{
            
            var comando = "Select nome,rg,email,telefone,Funcionario.endereco,cargo,senha,sexo,salario,estado_civil,cpf,Funcionario.idEmpresa,empresa.nomeEmpresa from Funcionario join empresa on empresa.idEmpresa = Funcionario.idEmpresa where cpf = " + pesquisaCpf + ";";
            this.conectar.executarSQL(comando);
            
             while (this.conectar.getResultSet().next()) {
                 novo.setNome(this.conectar.getResultSet().getString(1));
                 novo.setRg(this.conectar.getResultSet().getString(2));
                 novo.setEmail(this.conectar.getResultSet().getString(3));
                 novo.setTelefone(this.conectar.getResultSet().getString(4));
                 novo.setEndereco(this.conectar.getResultSet().getString(5));
                 novo.setCargo(this.conectar.getResultSet().getString(6));
                 novo.setSenha(this.conectar.getResultSet().getString(7));
                 novo.setSexo(this.conectar.getResultSet().getString(8));
                 novo.setSalario(this.conectar.getResultSet().getString(9));
                 novo.setEstado_civil(this.conectar.getResultSet().getString(10));
                 novo.setCpf(this.conectar.getResultSet().getString(11));
                 novo.setEmpresa(this.conectar.getResultSet().getInt(12));
                 novo.setNomeEmpresa(this.conectar.getResultSet().getString(13));
             }
             
             if(novo.getCpf() == ""){
                 JOptionPane.showMessageDialog(null, "Erro ao buscar Cliente");
             }
        }catch(Exception e){
            System.out.println("Erro ao consultar Cliente " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar Cliente");
        
        }finally{
                 txt_pesquisaNome.setText(novo.getNome());
                 txt_pesquisaRG.setText(novo.getRg());
                 txt_pesquisaEmail.setText(novo.getEmail());
                 txt_pesquisaTelefone.setText(novo.getTelefone());
                 txt_pesquisaEndereco.setText(novo.getEndereco());
                 txt_pesquisaCargo.setText(novo.getCargo());
                 txt_pesquisaSenha.setText(novo.getSenha());
                 txt_pesquisaSexo.setText(novo.getSexo());
                 txt_pesquisaSalario.setText(novo.getSalario());
                 txt_pesquisaEstadoCivil.setText(novo.getEstado_civil());
                 cmb_pesquisaEmpresa.addItem(novo.getNomeEmpresa());
                 
        }
        
    }
    
    private void CadastrarFuncionario(Funcionario novo){
        this.conectar.conectaBanco(); //estabelecendo conexão com o bd
        
        novo.setNome(txt_nome.getText());
        novo.setCpf(txt_Cpf.getText());
        novo.setSenha(txt_senha.getText());
        novo.setEmail(txt_email.getText());
        novo.setCargo(String.valueOf(cmb_cargo.getSelectedItem()));
        novo.setEndereco(txt_endereco.getText());
        novo.setEstado_civil(String.valueOf(cmb_estadoCivil.getSelectedItem()));
        novo.setSexo(String.valueOf(cmb_sexo.getSelectedItem()));
        novo.setRg(txt_rg.getText());
        novo.setSalario(txt_salario.getText());
        novo.setTelefone(txt_telefone.getText());
        novo.setEmpresa(cmb_Empresa.getSelectedIndex());
        
        try{
            var query = "INSERT INTO Funcionario(nome,rg,email,telefone,endereco,cargo,senha,sexo,cpf,salario,estado_civil,idEmpresa)"
                    + "values( '" + novo.getNome() + "',"
                    + "'"+ novo.getRg() + "',"
                    + "'"+ novo.getEmail() + "',"
                    + "'" + novo.getTelefone() + "',"
                    + "'" + novo.getEndereco() + "',"
                    + "'" + novo.getCargo() + "',"
                    + "'" + novo.getSenha() + "',"
                    + "'" + novo.getSexo() + "',"
                    + "'" + novo.getCpf() + "',"
                    + "'" + novo.getSalario() + "',"
                    + "' " + novo.getEstado_civil() +"',"
                    + "'" + novo.getEmpresa() + "');";
            
            this.conectar.insertSQL(query);
                    
            JOptionPane.showMessageDialog (null, "Cadastro Realizado com Sucesso!!");
        } catch (Exception e ){
            System.out.println("Erro ao Cadastrar Cliente  " + e.getMessage());
            JOptionPane.showMessageDialog (null, "Erro ao Cadastrar Funcionario!");
        } finally {
            this.conectar.fechaBanco ();
        }
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }
    
    public void Recebe(String user, String cargo){
        cargoRecebido = cargo;
        userRecebido = user;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_pesquisalimpar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<String> cmb_Empresa;
    private javax.swing.JComboBox<String> cmb_cargo;
    private javax.swing.JComboBox<String> cmb_estadoCivil;
    private javax.swing.JComboBox<String> cmb_pesquisaEmpresa;
    private javax.swing.JComboBox<String> cmb_sexo;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_Cpf;
    private javax.swing.JTextField txt_confirmaSenha;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_pesquisaCPF;
    private javax.swing.JTextField txt_pesquisaCargo;
    private javax.swing.JTextField txt_pesquisaEmail;
    private javax.swing.JTextField txt_pesquisaEndereco;
    private javax.swing.JTextField txt_pesquisaEstadoCivil;
    private javax.swing.JTextField txt_pesquisaNome;
    private javax.swing.JTextField txt_pesquisaRG;
    private javax.swing.JTextField txt_pesquisaSalario;
    private javax.swing.JTextField txt_pesquisaSenha;
    private javax.swing.JTextField txt_pesquisaSexo;
    private javax.swing.JTextField txt_pesquisaTelefone;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_salario;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

Vector<Integer> id_empresa = new Vector<Integer>();
   
    private void resgatarEmpresas(){
        this.conectar.conectaBanco();
        System.out.println("RODANDO RESGATAR EMPRESA");
        try{
            System.out.println("RODANDO O TRY");
            var query = "Select * from Empresa";
            
            this.conectar.executarSQL(query);
            
            while(this.conectar.getResultSet().next()){
                id_empresa.add(this.conectar.getResultSet().getInt(1));
                cmb_Empresa.addItem(this.conectar.getResultSet().getString(2));
            }
            System.out.println(conectar.getResultSet());
        }catch(Exception error){
            System.out.println("ALGUM ERRO ACONTECEU + " + error);
        }finally{
            
        }
    }
}
